# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: cd /home/ubuntu/dukandar-repos/sample-deploy
    - run: git fetch --prune --all
    - run: git checkout main
    - run: git reset --hard origin/main
    - run: git pull && npm i --only=prod
    - run: sudo docker rm -f sample-deploy
    - run: sudo docker rmi -f sample-deploy
    - run: echo 'About to build docker image'
    - run: sleep 10
    - run: (DOCKER_BUILDKIT=1 sudo docker build -t sample-deploy .) &&
    - run: (sudo docker run -d --name sample-deploy -p 3333:3333 sample-deploy:latest)
    - run: sleep 3
    - run: echo 'Deploying image on container .'
    - run: sleep 3
    - run: echo 'Deploying image in container ...'
    - run: curl http://localhost:3333/
